name: rawmid
description: "Rawmid"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.3
  http: ^1.2.0
  get: ^4.6.6
  shared_preferences: ^2.5.3
  pinput: ^5.0.0
  email_validator: ^3.0.0
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  url_launcher: ^6.3.1
  speech_to_text: ^7.0.0
  webview_flutter: ^4.10.0
  webview_flutter_wkwebview: ^3.18.5
  intl: ^0.19.0
  geolocator: ^13.0.2
  phone_form_field: ^10.0.4
  flutter_html: ^3.0.0-beta.2
  file_picker: ^10.1.0
  pdf: ^3.10.0
  printing: ^5.13.0
  screenshot: ^3.0.0
  flutter_typeahead: ^5.2.0
  flutter_localization: ^0.3.2
  flutter_html_iframe: ^3.0.0
  firebase_core: ^3.8.0
  firebase_messaging: ^15.2.4
  flutter_local_notifications: ^19.0.0
  flutter_inner_shadow: ^0.0.1
  yandex_mapkit: ^4.1.0
  share_plus: ^11.0.0
  path_provider: ^2.1.5
  ypay: ^1.0.3
  responsive_builder: ^0.7.1
  app_links: ^6.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/icon/icon.png"
  android_12:
    image_path: "assets/icon/icon.png"
    adaptive_icon_background: "#000000"
    adaptive_icon_foreground: "assets/icon/icon.png"

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/icon/
    - assets/image/